/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './components/**/*.{js,vue,ts}',
        './layouts/**/*.vue',
        './pages/**/*.vue',
        './plugins/**/*.{js,ts}',
        './app.vue',
    ],
    theme: {
        extend: {
            colors: {
                // Custom COVID dashboard colors
                'covid-blue': '#3b82f6',
                'covid-red': '#ef4444',
                'covid-green': '#22c55e',
                'covid-orange': '#f97316',
                'covid-purple': '#a855f7',
            },
        },
    },
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            {
                mytheme: {
                    "primary": "oklch(55% 0.3 240)",
                    "primary-content": "oklch(98% 0.01 240)",
                    "secondary": "oklch(70% 0.25 200)",
                    "secondary-content": "oklch(98% 0.01 200)",
                    "accent": "oklch(65% 0.25 160)",
                    "accent-content": "oklch(98% 0.01 160)",
                    "neutral": "oklch(50% 0.05 240)",
                    "neutral-content": "oklch(98% 0.01 240)",
                    "base-100": "oklch(98% 0.02 240)",
                    "base-200": "oklch(95% 0.03 240)",
                    "base-300": "oklch(92% 0.04 240)",
                    "base-content": "oklch(20% 0.05 240)",
                    "info": "oklch(70% 0.2 220)",
                    "info-content": "oklch(98% 0.01 220)",
                    "success": "oklch(65% 0.25 140)",
                    "success-content": "oklch(98% 0.01 140)",
                    "warning": "oklch(80% 0.25 80)",
                    "warning-content": "oklch(20% 0.05 80)",
                    "error": "oklch(65% 0.3 30)",
                    "error-content": "oklch(98% 0.01 30)",
                    "--radius-selector": "1rem",
                    "--radius-field": "0.25rem",
                    "--radius-box": "0.5rem",
                    "--size-selector": "0.25rem",
                    "--size-field": "0.25rem",
                    "--border": "1px",
                    "--depth": "1",
                    "--noise": "0",
                },
            },
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
        darkTheme: 'dark', // Changed from covidDark to standard dark since we're using all themes
    },
};
